"""empty message

Revision ID: 02dec8b263ba
Revises: a3c810183618
Create Date: 2023-10-20 09:31:55.130531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02dec8b263ba'
down_revision = 'a3c810183618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritoPeoles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('peoples_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['peoples_id'], ['peoples.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favPeoles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favPeoles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"favPeoles_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peoples_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['peoples_id'], ['peoples.id'], name='favPeoles_peoples_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favPeoles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favPeoles_pkey')
    )
    op.drop_table('favoritoPeoles')
    # ### end Alembic commands ###
